### ISSUE TITLE
哥，你是怎么学习这个项目的

### ISSUE THREAD

**Issue by woaichijitui** [bugplus-free/looklook#3]
视频基本介绍，里面具体代码不知道怎么一步一步写下来的。查看了最开始的版本也是写了大部分代码

**Comment by bugplus-free** [comment]
你好，这个项目我也并不是独立写完，应为这个项目是使用了工具来进行实现的，可能会应为版本的不同会出现一定的问题。对于该项目学习我的想法是聚焦于思维方面，了解整体板块与板块之间的交互就已经算是达到很好的效果了，rpc方面也就是消息的发送与接受，可以找好的代码直接进行学习思路其实就比较OK了

**Comment by bugplus-free** [comment]
> 视频基本介绍，里面具体代码不知道怎么一步一步写下来的。查看了最开始的版

> 视频基本介绍，里面具体代码不知道怎么一步一步写下来的。查看了最开始的版本也是写了大部分代码

你好，这个项目我也并不是独立写完，应为这个项目是使用了工具来进行实现的，可能会应为版本的不同会出现一定的问题。对于该项目学习我的想法是聚焦于思维方面，了解整体板块与板块之间的交互就已经算是达到很好的效果了，rpc方面也就是消息的发送与接受，可以找好的代码直接进行学习思路其实就比较OK了
